controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_base_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_base_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    # Use /cmd_vel directly from teleop
    cmd_vel_topic: "/cmd_vel"
    use_stamped_vel: false

    publish_rate: 50.0
    cmd_vel_timeout: 0.25

    base_frame_id: "base_link"
    odom_frame_id: "odom"

    # You can tune these if needed
    wheel_separation: 0.28
    wheel_radius: 0.07

    enable_odom_tf: true
    pose_covariance_diagonal: [0.001, 0.001, 1000.0, 1000.0, 1000.0, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 1000.0, 1000.0, 1000.0, 0.01]
